name: hse_shop

services:

  ordersdb:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ordersdb_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d orders" ]
      interval: 5s
      timeout: 3s
      retries: 20
  
  
  paymentsdb:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"   
    volumes:
      - paymentsdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payments"]
      interval: 5s
      timeout: 3s
      retries: 20

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD-SHELL", "bash -ec 'echo ruok > /dev/tcp/127.0.0.1/2181'" ]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
  
  
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"  
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s

  ordersservice:
    build:
      context: .
      dockerfile: OrdersService/Dockerfile
    depends_on:
      ordersdb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Db: Host=ordersdb;Port=5432;Database=orders;Username=postgres;Password=postgres
      Kafka__BootstrapServers: kafka:29092
    ports:
      - "8081:8080"

  paymentsservice:
    build:
      context: .
      dockerfile: PaymentsService/Dockerfile
    depends_on:
      paymentsdb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Db: Host=paymentsdb;Port=5432;Database=payments;Username=postgres;Password=postgres
      Kafka__BootstrapServers: kafka:29092
      Kafka__OrderPaymentRequestedTopic: order.payment.requested
      Kafka__PaymentResultTopic: payment.result
      Kafka__ConsumerGroupId: payments-service
    ports:
      - "8082:8080"

  gatewayservice:
    build:
      context: .
      dockerfile: GatewayService/Dockerfile
    depends_on:
      ordersservice:
        condition: service_started
      paymentsservice:
        condition: service_started
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      OrdersService__BaseUrl: http://ordersservice:8080
      PaymentsService__BaseUrl: http://paymentsservice:8080
    ports:
      - "8080:8080"

  frontendservice:
    build:
      context: .
      dockerfile: FrontendService/Dockerfile
    depends_on:
      gatewayservice:
        condition: service_started
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      Gateway__BaseUrl: http://gatewayservice:8080
    ports:
      - "8083:8080"

volumes:
  ordersdb_data:
  paymentsdb_data:
